language: php

php:
  - 7.2
  - 7.3

sudo: false

env:
  matrix:
    - DB=mysql db_dsn='mysql://travis@0.0.0.0/cakephp_test'
    - DB=pgsql db_dsn='postgres://travis@127.0.0.1/cakephp_test'
    - DB=sqlite db_dsn='sqlite:///:memory:'
  global:
    - DEFAULT=1

matrix:
  allow_failures:
    - php: hhvm-nightly
  fast_finish: true
  include:
    - php: 7.3
      env: PHPCS=1 DEFAULT=0

    - php: 7.3
      env: COVERAGE=1 DEFAULT=0 DB=mysql db_dsn='mysql://travis@0.0.0.0/cakephp_test'
      
before_script:
  - sh -c "composer install --no-interaction --dev"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi"
  - if [[ $PHPSTAN = 1 ]]; then composer stan-setup; fi

  - phpenv rehash
  - set +H

script:
  - if [[ $DEFAULT = 1 ]]; then composer test; fi
  - if [[ $COVERAGE = 1 ]]; then composer coverage-test; fi
  - if [[ $PHPCS = 1 ]]; then composer cs-check; fi
  - if [[ $PHPSTAN = 1 ]]; then composer stan; fi

after_success:
  - if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi
  
notifications:
  email: false
